title: "Onlooker & Cutelooker"
author:
  name: ""
description: ""
remote_theme: jekyll/minima

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      image: https://denuvosoftwaresolutions.github.io/Onlooker/Cutelooker-example.png
      description: "Simple memory profiler for Windows."

header_pages:
  - ""

minima:
  # generate social links in footer
  social_links:
    twitter: gamingatdenuvo
    github:  denuvosoftwaresolutions
    linkedincompany: denuvo-gmbh
