title: "Onlooker & Cutelooker"
author:
  name: "Anti-Tamper Team @ Denuvo"
description: "Simple memory profiler for Windows"
remote_theme: jekyll/minima@v2.5.2

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      image: https://denuvosoftwaresolutions.github.io/Onlooker/Cutelooker-example.png
      description: "Simple memory profiler for Windows"

header_pages:
  -

minima:
  # generate social links in footer
  social_links:
    twitter: gamingatdenuvo
    github:  denuvosoftwaresolutions
    linkedincompany: denuvo-gmbh

plugins:
  - jekyll-default-layout
  - jekyll-remote-theme
  - jekyll-optional-front-matter
